
project_id = "mcoeiucylazrjvhaemmc"
[api]
enabled = true
[db]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[edge_functions]
enabled = true
[functions.fetch_user_rankings]
verify_jwt = false
