
project_id = "mcoeiucylazrjvhaemmc"
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[realtime]
enabled = true

[functions.fix-user-stats]
verify_jwt = true

[functions.generate-verse]
verify_jwt = true
