
project_id = "mcoeiucylazrjvhaemmc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[edge_functions]
enabled = true

[auth]
enabled = true
email = ["en", "pt"]
